"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import google.protobuf.timestamp_pb2
import sys
import typing
import xyz.block.ftl.v1.schema.schema_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DeploymentChangeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DeploymentChangeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DeploymentChangeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEPLOYMENT_ADDED: _DeploymentChangeType.ValueType  # 0
    DEPLOYMENT_REMOVED: _DeploymentChangeType.ValueType  # 1
    DEPLOYMENT_CHANGED: _DeploymentChangeType.ValueType  # 2

class DeploymentChangeType(_DeploymentChangeType, metaclass=_DeploymentChangeTypeEnumTypeWrapper): ...

DEPLOYMENT_ADDED: DeploymentChangeType.ValueType  # 0
DEPLOYMENT_REMOVED: DeploymentChangeType.ValueType  # 1
DEPLOYMENT_CHANGED: DeploymentChangeType.ValueType  # 2
global___DeploymentChangeType = DeploymentChangeType

class _ConfigProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConfigProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConfigProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONFIG_INLINE: _ConfigProvider.ValueType  # 0
    """Write values inline in the configuration file."""
    CONFIG_ENVAR: _ConfigProvider.ValueType  # 1
    """Print configuration as environment variables."""
    CONFIG_DB: _ConfigProvider.ValueType  # 2
    """Use the database as a configuration store."""

class ConfigProvider(_ConfigProvider, metaclass=_ConfigProviderEnumTypeWrapper): ...

CONFIG_INLINE: ConfigProvider.ValueType  # 0
"""Write values inline in the configuration file."""
CONFIG_ENVAR: ConfigProvider.ValueType  # 1
"""Print configuration as environment variables."""
CONFIG_DB: ConfigProvider.ValueType  # 2
"""Use the database as a configuration store."""
global___ConfigProvider = ConfigProvider

class _SecretProvider:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SecretProviderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SecretProvider.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SECRET_INLINE: _SecretProvider.ValueType  # 0
    """Write values inline in the configuration file."""
    SECRET_ENVAR: _SecretProvider.ValueType  # 1
    """Print configuration as environment variables."""
    SECRET_KEYCHAIN: _SecretProvider.ValueType  # 2
    """Write to the system keychain."""
    SECRET_OP: _SecretProvider.ValueType  # 3
    """Store a secret in the 1Password vault."""
    SECRET_ASM: _SecretProvider.ValueType  # 4
    """Store a secret in the AWS Secrets Manager."""

class SecretProvider(_SecretProvider, metaclass=_SecretProviderEnumTypeWrapper): ...

SECRET_INLINE: SecretProvider.ValueType  # 0
"""Write values inline in the configuration file."""
SECRET_ENVAR: SecretProvider.ValueType  # 1
"""Print configuration as environment variables."""
SECRET_KEYCHAIN: SecretProvider.ValueType  # 2
"""Write to the system keychain."""
SECRET_OP: SecretProvider.ValueType  # 3
"""Store a secret in the 1Password vault."""
SECRET_ASM: SecretProvider.ValueType  # 4
"""Store a secret in the AWS Secrets Manager."""
global___SecretProvider = SecretProvider

@typing.final
class PingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PingRequest = PingRequest

@typing.final
class PingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NOT_READY_FIELD_NUMBER: builtins.int
    not_ready: builtins.str
    """If present, the service is not ready to accept requests and this is the
    reason.
    """
    def __init__(
        self,
        *,
        not_ready: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_not_ready", b"_not_ready", "not_ready", b"not_ready"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_not_ready", b"_not_ready", "not_ready", b"not_ready"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_not_ready", b"_not_ready"]) -> typing.Literal["not_ready"] | None: ...

global___PingResponse = PingResponse

@typing.final
class ModuleContextRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    module: builtins.str
    def __init__(
        self,
        *,
        module: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["module", b"module"]) -> None: ...

global___ModuleContextRequest = ModuleContextRequest

@typing.final
class ModuleContextResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _DBType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DBTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ModuleContextResponse._DBType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POSTGRES: ModuleContextResponse._DBType.ValueType  # 0

    class DBType(_DBType, metaclass=_DBTypeEnumTypeWrapper): ...
    POSTGRES: ModuleContextResponse.DBType.ValueType  # 0

    @typing.final
    class Ref(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODULE_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        module: builtins.str
        name: builtins.str
        def __init__(
            self,
            *,
            module: builtins.str | None = ...,
            name: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_module", b"_module", "module", b"module"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_module", b"_module", "module", b"module", "name", b"name"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_module", b"_module"]) -> typing.Literal["module"] | None: ...

    @typing.final
    class DSN(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        TYPE_FIELD_NUMBER: builtins.int
        DSN_FIELD_NUMBER: builtins.int
        name: builtins.str
        type: global___ModuleContextResponse.DBType.ValueType
        dsn: builtins.str
        def __init__(
            self,
            *,
            name: builtins.str = ...,
            type: global___ModuleContextResponse.DBType.ValueType = ...,
            dsn: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["dsn", b"dsn", "name", b"name", "type", b"type"]) -> None: ...

    @typing.final
    class ConfigsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class SecretsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MODULE_FIELD_NUMBER: builtins.int
    CONFIGS_FIELD_NUMBER: builtins.int
    SECRETS_FIELD_NUMBER: builtins.int
    DATABASES_FIELD_NUMBER: builtins.int
    module: builtins.str
    @property
    def configs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]: ...
    @property
    def secrets(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]: ...
    @property
    def databases(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModuleContextResponse.DSN]: ...
    def __init__(
        self,
        *,
        module: builtins.str = ...,
        configs: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
        secrets: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
        databases: collections.abc.Iterable[global___ModuleContextResponse.DSN] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configs", b"configs", "databases", b"databases", "module", b"module", "secrets", b"secrets"]) -> None: ...

global___ModuleContextResponse = ModuleContextResponse

@typing.final
class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Pair(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Metadata.Pair]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___Metadata.Pair] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___Metadata = Metadata

@typing.final
class CallRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    METADATA_FIELD_NUMBER: builtins.int
    VERB_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    body: builtins.bytes
    @property
    def metadata(self) -> global___Metadata: ...
    @property
    def verb(self) -> xyz.block.ftl.v1.schema.schema_pb2.Ref: ...
    def __init__(
        self,
        *,
        metadata: global___Metadata | None = ...,
        verb: xyz.block.ftl.v1.schema.schema_pb2.Ref | None = ...,
        body: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "verb", b"verb"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "metadata", b"metadata", "verb", b"verb"]) -> None: ...

global___CallRequest = CallRequest

@typing.final
class CallResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Error(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MESSAGE_FIELD_NUMBER: builtins.int
        STACK_FIELD_NUMBER: builtins.int
        message: builtins.str
        stack: builtins.str
        """TODO: Richer error type."""
        def __init__(
            self,
            *,
            message: builtins.str = ...,
            stack: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_stack", b"_stack", "stack", b"stack"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_stack", b"_stack", "message", b"message", "stack", b"stack"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_stack", b"_stack"]) -> typing.Literal["stack"] | None: ...

    BODY_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    body: builtins.bytes
    @property
    def error(self) -> global___CallResponse.Error: ...
    def __init__(
        self,
        *,
        body: builtins.bytes = ...,
        error: global___CallResponse.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["body", b"body", "error", b"error", "response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "error", b"error", "response", b"response"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["response", b"response"]) -> typing.Literal["body", "error"] | None: ...

global___CallResponse = CallResponse

@typing.final
class AcquireLeaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    module: builtins.str
    @property
    def key(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def ttl(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        module: builtins.str = ...,
        key: collections.abc.Iterable[builtins.str] | None = ...,
        ttl: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ttl", b"ttl"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "module", b"module", "ttl", b"ttl"]) -> None: ...

global___AcquireLeaseRequest = AcquireLeaseRequest

@typing.final
class AcquireLeaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___AcquireLeaseResponse = AcquireLeaseResponse

@typing.final
class SendFSMEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FSM_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    instance: builtins.str
    body: builtins.bytes
    @property
    def fsm(self) -> xyz.block.ftl.v1.schema.schema_pb2.Ref: ...
    @property
    def event(self) -> xyz.block.ftl.v1.schema.schema_pb2.Type: ...
    def __init__(
        self,
        *,
        fsm: xyz.block.ftl.v1.schema.schema_pb2.Ref | None = ...,
        instance: builtins.str = ...,
        event: xyz.block.ftl.v1.schema.schema_pb2.Type | None = ...,
        body: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["event", b"event", "fsm", b"fsm"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "event", b"event", "fsm", b"fsm", "instance", b"instance"]) -> None: ...

global___SendFSMEventRequest = SendFSMEventRequest

@typing.final
class SendFSMEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SendFSMEventResponse = SendFSMEventResponse

@typing.final
class PublishEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOPIC_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    CALLER_FIELD_NUMBER: builtins.int
    body: builtins.bytes
    caller: builtins.str
    """Only verb name is included because this verb will be in the same module as topic"""
    @property
    def topic(self) -> xyz.block.ftl.v1.schema.schema_pb2.Ref: ...
    def __init__(
        self,
        *,
        topic: xyz.block.ftl.v1.schema.schema_pb2.Ref | None = ...,
        body: builtins.bytes = ...,
        caller: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["topic", b"topic"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["body", b"body", "caller", b"caller", "topic", b"topic"]) -> None: ...

global___PublishEventRequest = PublishEventRequest

@typing.final
class PublishEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PublishEventResponse = PublishEventResponse

@typing.final
class GetCertificationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    signature: builtins.bytes
    @property
    def request(self) -> global___CertificateContent: ...
    def __init__(
        self,
        *,
        request: global___CertificateContent | None = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["request", b"request", "signature", b"signature"]) -> None: ...

global___GetCertificationRequest = GetCertificationRequest

@typing.final
class GetCertificationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CERTIFICATE_FIELD_NUMBER: builtins.int
    @property
    def certificate(self) -> global___Certificate: ...
    def __init__(
        self,
        *,
        certificate: global___Certificate | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["certificate", b"certificate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["certificate", b"certificate"]) -> None: ...

global___GetCertificationResponse = GetCertificationResponse

@typing.final
class CertificateContent(google.protobuf.message.Message):
    """CertificateContent is separated from Certificate to allow for easier signing."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTITY_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    identity: builtins.str
    public_key: builtins.bytes
    def __init__(
        self,
        *,
        identity: builtins.str = ...,
        public_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["identity", b"identity", "public_key", b"public_key"]) -> None: ...

global___CertificateContent = CertificateContent

@typing.final
class Certificate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    CONTROLLER_SIGNATURE_FIELD_NUMBER: builtins.int
    controller_signature: builtins.bytes
    @property
    def content(self) -> global___CertificateContent: ...
    def __init__(
        self,
        *,
        content: global___CertificateContent | None = ...,
        controller_signature: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content", b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "controller_signature", b"controller_signature"]) -> None: ...

global___Certificate = Certificate

@typing.final
class GetSchemaRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetSchemaRequest = GetSchemaRequest

@typing.final
class GetSchemaResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: builtins.int
    @property
    def schema(self) -> xyz.block.ftl.v1.schema.schema_pb2.Schema: ...
    def __init__(
        self,
        *,
        schema: xyz.block.ftl.v1.schema.schema_pb2.Schema | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["schema", b"schema"]) -> None: ...

global___GetSchemaResponse = GetSchemaResponse

@typing.final
class PullSchemaRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PullSchemaRequest = PullSchemaRequest

@typing.final
class PullSchemaResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    MODULE_NAME_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    MORE_FIELD_NUMBER: builtins.int
    CHANGE_TYPE_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    module_name: builtins.str
    more: builtins.bool
    """If true there are more schema changes immediately following this one as part of the initial batch.
    If false this is the last schema change in the initial batch, but others may follow later.
    """
    change_type: global___DeploymentChangeType.ValueType
    @property
    def schema(self) -> xyz.block.ftl.v1.schema.schema_pb2.Module:
        """For deletes this will not be present."""

    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        module_name: builtins.str = ...,
        schema: xyz.block.ftl.v1.schema.schema_pb2.Module | None = ...,
        more: builtins.bool = ...,
        change_type: global___DeploymentChangeType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_schema", b"_schema", "schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_schema", b"_schema", "change_type", b"change_type", "deployment_key", b"deployment_key", "module_name", b"module_name", "more", b"more", "schema", b"schema"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_schema", b"_schema"]) -> typing.Literal["schema"] | None: ...

global___PullSchemaResponse = PullSchemaResponse

@typing.final
class GetArtefactDiffsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_DIGESTS_FIELD_NUMBER: builtins.int
    @property
    def client_digests(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        client_digests: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_digests", b"client_digests"]) -> None: ...

global___GetArtefactDiffsRequest = GetArtefactDiffsRequest

@typing.final
class GetArtefactDiffsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MISSING_DIGESTS_FIELD_NUMBER: builtins.int
    CLIENT_ARTEFACTS_FIELD_NUMBER: builtins.int
    @property
    def missing_digests(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def client_artefacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentArtefact]:
        """Artefacts that the client already has, and their path+executable status."""

    def __init__(
        self,
        *,
        missing_digests: collections.abc.Iterable[builtins.str] | None = ...,
        client_artefacts: collections.abc.Iterable[global___DeploymentArtefact] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["client_artefacts", b"client_artefacts", "missing_digests", b"missing_digests"]) -> None: ...

global___GetArtefactDiffsResponse = GetArtefactDiffsResponse

@typing.final
class UploadArtefactRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    content: builtins.bytes
    def __init__(
        self,
        *,
        content: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content"]) -> None: ...

global___UploadArtefactRequest = UploadArtefactRequest

@typing.final
class UploadArtefactResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DIGEST_FIELD_NUMBER: builtins.int
    digest: builtins.bytes
    def __init__(
        self,
        *,
        digest: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["digest", b"digest"]) -> None: ...

global___UploadArtefactResponse = UploadArtefactResponse

@typing.final
class DeploymentArtefact(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DIGEST_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    EXECUTABLE_FIELD_NUMBER: builtins.int
    digest: builtins.str
    path: builtins.str
    executable: builtins.bool
    def __init__(
        self,
        *,
        digest: builtins.str = ...,
        path: builtins.str = ...,
        executable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["digest", b"digest", "executable", b"executable", "path", b"path"]) -> None: ...

global___DeploymentArtefact = DeploymentArtefact

@typing.final
class CreateDeploymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: builtins.int
    ARTEFACTS_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    @property
    def schema(self) -> xyz.block.ftl.v1.schema.schema_pb2.Module: ...
    @property
    def artefacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentArtefact]: ...
    @property
    def labels(self) -> google.protobuf.struct_pb2.Struct:
        """Runner labels required to run this deployment."""

    def __init__(
        self,
        *,
        schema: xyz.block.ftl.v1.schema.schema_pb2.Module | None = ...,
        artefacts: collections.abc.Iterable[global___DeploymentArtefact] | None = ...,
        labels: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_labels", b"_labels", "labels", b"labels", "schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_labels", b"_labels", "artefacts", b"artefacts", "labels", b"labels", "schema", b"schema"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_labels", b"_labels"]) -> typing.Literal["labels"] | None: ...

global___CreateDeploymentRequest = CreateDeploymentRequest

@typing.final
class CreateDeploymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    ACTIVE_DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    active_deployment_key: builtins.str
    """Currently active deployment for this module, if any."""
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        active_deployment_key: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_active_deployment_key", b"_active_deployment_key", "active_deployment_key", b"active_deployment_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_active_deployment_key", b"_active_deployment_key", "active_deployment_key", b"active_deployment_key", "deployment_key", b"deployment_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_active_deployment_key", b"_active_deployment_key"]) -> typing.Literal["active_deployment_key"] | None: ...

global___CreateDeploymentResponse = CreateDeploymentResponse

@typing.final
class GetDeploymentArtefactsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    HAVE_ARTEFACTS_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    @property
    def have_artefacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentArtefact]: ...
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        have_artefacts: collections.abc.Iterable[global___DeploymentArtefact] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deployment_key", b"deployment_key", "have_artefacts", b"have_artefacts"]) -> None: ...

global___GetDeploymentArtefactsRequest = GetDeploymentArtefactsRequest

@typing.final
class GetDeploymentArtefactsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARTEFACT_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    chunk: builtins.bytes
    @property
    def artefact(self) -> global___DeploymentArtefact: ...
    def __init__(
        self,
        *,
        artefact: global___DeploymentArtefact | None = ...,
        chunk: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["artefact", b"artefact"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artefact", b"artefact", "chunk", b"chunk"]) -> None: ...

global___GetDeploymentArtefactsResponse = GetDeploymentArtefactsResponse

@typing.final
class GetDeploymentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deployment_key", b"deployment_key"]) -> None: ...

global___GetDeploymentRequest = GetDeploymentRequest

@typing.final
class GetDeploymentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: builtins.int
    ARTEFACTS_FIELD_NUMBER: builtins.int
    @property
    def schema(self) -> xyz.block.ftl.v1.schema.schema_pb2.Module: ...
    @property
    def artefacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeploymentArtefact]: ...
    def __init__(
        self,
        *,
        schema: xyz.block.ftl.v1.schema.schema_pb2.Module | None = ...,
        artefacts: collections.abc.Iterable[global___DeploymentArtefact] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artefacts", b"artefacts", "schema", b"schema"]) -> None: ...

global___GetDeploymentResponse = GetDeploymentResponse

@typing.final
class RegisterRunnerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    DEPLOYMENT_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    key: builtins.str
    endpoint: builtins.str
    deployment: builtins.str
    @property
    def labels(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        endpoint: builtins.str = ...,
        deployment: builtins.str = ...,
        labels: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["labels", b"labels"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["deployment", b"deployment", "endpoint", b"endpoint", "key", b"key", "labels", b"labels"]) -> None: ...

global___RegisterRunnerRequest = RegisterRunnerRequest

@typing.final
class RegisterRunnerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RegisterRunnerResponse = RegisterRunnerResponse

@typing.final
class UpdateDeployRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    MIN_REPLICAS_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    min_replicas: builtins.int
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        min_replicas: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deployment_key", b"deployment_key", "min_replicas", b"min_replicas"]) -> None: ...

global___UpdateDeployRequest = UpdateDeployRequest

@typing.final
class UpdateDeployResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateDeployResponse = UpdateDeployResponse

@typing.final
class ReplaceDeployRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    MIN_REPLICAS_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    min_replicas: builtins.int
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        min_replicas: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deployment_key", b"deployment_key", "min_replicas", b"min_replicas"]) -> None: ...

global___ReplaceDeployRequest = ReplaceDeployRequest

@typing.final
class ReplaceDeployResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ReplaceDeployResponse = ReplaceDeployResponse

@typing.final
class StreamDeploymentLogsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AttributesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
    REQUEST_KEY_FIELD_NUMBER: builtins.int
    TIME_STAMP_FIELD_NUMBER: builtins.int
    LOG_LEVEL_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    deployment_key: builtins.str
    request_key: builtins.str
    log_level: builtins.int
    message: builtins.str
    error: builtins.str
    @property
    def time_stamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def attributes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        deployment_key: builtins.str = ...,
        request_key: builtins.str | None = ...,
        time_stamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        log_level: builtins.int = ...,
        attributes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        message: builtins.str = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error", b"_error", "_request_key", b"_request_key", "error", b"error", "request_key", b"request_key", "time_stamp", b"time_stamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_error", b"_error", "_request_key", b"_request_key", "attributes", b"attributes", "deployment_key", b"deployment_key", "error", b"error", "log_level", b"log_level", "message", b"message", "request_key", b"request_key", "time_stamp", b"time_stamp"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_request_key", b"_request_key"]) -> typing.Literal["request_key"] | None: ...

global___StreamDeploymentLogsRequest = StreamDeploymentLogsRequest

@typing.final
class StreamDeploymentLogsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StreamDeploymentLogsResponse = StreamDeploymentLogsResponse

@typing.final
class StatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StatusRequest = StatusRequest

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Controller(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        ENDPOINT_FIELD_NUMBER: builtins.int
        VERSION_FIELD_NUMBER: builtins.int
        key: builtins.str
        endpoint: builtins.str
        version: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            endpoint: builtins.str = ...,
            version: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["endpoint", b"endpoint", "key", b"key", "version", b"version"]) -> None: ...

    @typing.final
    class Runner(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        LANGUAGES_FIELD_NUMBER: builtins.int
        ENDPOINT_FIELD_NUMBER: builtins.int
        DEPLOYMENT_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        key: builtins.str
        endpoint: builtins.str
        deployment: builtins.str
        @property
        def languages(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        @property
        def labels(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            languages: collections.abc.Iterable[builtins.str] | None = ...,
            endpoint: builtins.str = ...,
            deployment: builtins.str | None = ...,
            labels: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_deployment", b"_deployment", "deployment", b"deployment", "labels", b"labels"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_deployment", b"_deployment", "deployment", b"deployment", "endpoint", b"endpoint", "key", b"key", "labels", b"labels", "languages", b"languages"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_deployment", b"_deployment"]) -> typing.Literal["deployment"] | None: ...

    @typing.final
    class Deployment(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        LANGUAGE_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        MIN_REPLICAS_FIELD_NUMBER: builtins.int
        REPLICAS_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        SCHEMA_FIELD_NUMBER: builtins.int
        key: builtins.str
        language: builtins.str
        name: builtins.str
        min_replicas: builtins.int
        replicas: builtins.int
        @property
        def labels(self) -> google.protobuf.struct_pb2.Struct: ...
        @property
        def schema(self) -> xyz.block.ftl.v1.schema.schema_pb2.Module: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            language: builtins.str = ...,
            name: builtins.str = ...,
            min_replicas: builtins.int = ...,
            replicas: builtins.int = ...,
            labels: google.protobuf.struct_pb2.Struct | None = ...,
            schema: xyz.block.ftl.v1.schema.schema_pb2.Module | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["labels", b"labels", "schema", b"schema"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "labels", b"labels", "language", b"language", "min_replicas", b"min_replicas", "name", b"name", "replicas", b"replicas", "schema", b"schema"]) -> None: ...

    @typing.final
    class IngressRoute(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DEPLOYMENT_KEY_FIELD_NUMBER: builtins.int
        VERB_FIELD_NUMBER: builtins.int
        METHOD_FIELD_NUMBER: builtins.int
        PATH_FIELD_NUMBER: builtins.int
        deployment_key: builtins.str
        method: builtins.str
        path: builtins.str
        @property
        def verb(self) -> xyz.block.ftl.v1.schema.schema_pb2.Ref: ...
        def __init__(
            self,
            *,
            deployment_key: builtins.str = ...,
            verb: xyz.block.ftl.v1.schema.schema_pb2.Ref | None = ...,
            method: builtins.str = ...,
            path: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["verb", b"verb"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["deployment_key", b"deployment_key", "method", b"method", "path", b"path", "verb", b"verb"]) -> None: ...

    @typing.final
    class Route(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODULE_FIELD_NUMBER: builtins.int
        DEPLOYMENT_FIELD_NUMBER: builtins.int
        ENDPOINT_FIELD_NUMBER: builtins.int
        module: builtins.str
        deployment: builtins.str
        endpoint: builtins.str
        def __init__(
            self,
            *,
            module: builtins.str = ...,
            deployment: builtins.str = ...,
            endpoint: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["deployment", b"deployment", "endpoint", b"endpoint", "module", b"module"]) -> None: ...

    CONTROLLERS_FIELD_NUMBER: builtins.int
    RUNNERS_FIELD_NUMBER: builtins.int
    DEPLOYMENTS_FIELD_NUMBER: builtins.int
    INGRESS_ROUTES_FIELD_NUMBER: builtins.int
    ROUTES_FIELD_NUMBER: builtins.int
    @property
    def controllers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusResponse.Controller]: ...
    @property
    def runners(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusResponse.Runner]: ...
    @property
    def deployments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusResponse.Deployment]: ...
    @property
    def ingress_routes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusResponse.IngressRoute]: ...
    @property
    def routes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StatusResponse.Route]: ...
    def __init__(
        self,
        *,
        controllers: collections.abc.Iterable[global___StatusResponse.Controller] | None = ...,
        runners: collections.abc.Iterable[global___StatusResponse.Runner] | None = ...,
        deployments: collections.abc.Iterable[global___StatusResponse.Deployment] | None = ...,
        ingress_routes: collections.abc.Iterable[global___StatusResponse.IngressRoute] | None = ...,
        routes: collections.abc.Iterable[global___StatusResponse.Route] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["controllers", b"controllers", "deployments", b"deployments", "ingress_routes", b"ingress_routes", "routes", b"routes", "runners", b"runners"]) -> None: ...

global___StatusResponse = StatusResponse

@typing.final
class ProcessListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ProcessListRequest = ProcessListRequest

@typing.final
class ProcessListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ProcessRunner(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        ENDPOINT_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        key: builtins.str
        endpoint: builtins.str
        @property
        def labels(self) -> google.protobuf.struct_pb2.Struct: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            endpoint: builtins.str = ...,
            labels: google.protobuf.struct_pb2.Struct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["labels", b"labels"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["endpoint", b"endpoint", "key", b"key", "labels", b"labels"]) -> None: ...

    @typing.final
    class Process(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DEPLOYMENT_FIELD_NUMBER: builtins.int
        MIN_REPLICAS_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        RUNNER_FIELD_NUMBER: builtins.int
        deployment: builtins.str
        min_replicas: builtins.int
        @property
        def labels(self) -> google.protobuf.struct_pb2.Struct: ...
        @property
        def runner(self) -> global___ProcessListResponse.ProcessRunner: ...
        def __init__(
            self,
            *,
            deployment: builtins.str = ...,
            min_replicas: builtins.int = ...,
            labels: google.protobuf.struct_pb2.Struct | None = ...,
            runner: global___ProcessListResponse.ProcessRunner | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_runner", b"_runner", "labels", b"labels", "runner", b"runner"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_runner", b"_runner", "deployment", b"deployment", "labels", b"labels", "min_replicas", b"min_replicas", "runner", b"runner"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_runner", b"_runner"]) -> typing.Literal["runner"] | None: ...

    PROCESSES_FIELD_NUMBER: builtins.int
    @property
    def processes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProcessListResponse.Process]: ...
    def __init__(
        self,
        *,
        processes: collections.abc.Iterable[global___ProcessListResponse.Process] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["processes", b"processes"]) -> None: ...

global___ProcessListResponse = ProcessListResponse

@typing.final
class ResetSubscriptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_FIELD_NUMBER: builtins.int
    @property
    def subscription(self) -> xyz.block.ftl.v1.schema.schema_pb2.Ref: ...
    def __init__(
        self,
        *,
        subscription: xyz.block.ftl.v1.schema.schema_pb2.Ref | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["subscription", b"subscription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["subscription", b"subscription"]) -> None: ...

global___ResetSubscriptionRequest = ResetSubscriptionRequest

@typing.final
class ResetSubscriptionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ResetSubscriptionResponse = ResetSubscriptionResponse

@typing.final
class ConfigRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    module: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        module: builtins.str | None = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_module", b"_module", "module", b"module"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_module", b"_module", "module", b"module", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_module", b"_module"]) -> typing.Literal["module"] | None: ...

global___ConfigRef = ConfigRef

@typing.final
class ListConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    INCLUDE_VALUES_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    module: builtins.str
    include_values: builtins.bool
    provider: global___ConfigProvider.ValueType
    def __init__(
        self,
        *,
        module: builtins.str | None = ...,
        include_values: builtins.bool | None = ...,
        provider: global___ConfigProvider.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_include_values", b"_include_values", "_module", b"_module", "_provider", b"_provider", "include_values", b"include_values", "module", b"module", "provider", b"provider"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_include_values", b"_include_values", "_module", b"_module", "_provider", b"_provider", "include_values", b"include_values", "module", b"module", "provider", b"provider"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_include_values", b"_include_values"]) -> typing.Literal["include_values"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_module", b"_module"]) -> typing.Literal["module"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___ListConfigRequest = ListConfigRequest

@typing.final
class ListConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Config(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REFPATH_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        refPath: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            refPath: builtins.str = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_value", b"_value", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_value", b"_value", "refPath", b"refPath", "value", b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_value", b"_value"]) -> typing.Literal["value"] | None: ...

    CONFIGS_FIELD_NUMBER: builtins.int
    @property
    def configs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListConfigResponse.Config]: ...
    def __init__(
        self,
        *,
        configs: collections.abc.Iterable[global___ListConfigResponse.Config] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configs", b"configs"]) -> None: ...

global___ListConfigResponse = ListConfigResponse

@typing.final
class GetConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REF_FIELD_NUMBER: builtins.int
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        ref: global___ConfigRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ref", b"ref"]) -> None: ...

global___GetConfigRequest = GetConfigRequest

@typing.final
class GetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.bytes
    def __init__(
        self,
        *,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___GetConfigResponse = GetConfigResponse

@typing.final
class SetConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROVIDER_FIELD_NUMBER: builtins.int
    REF_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    provider: global___ConfigProvider.ValueType
    value: builtins.bytes
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        provider: global___ConfigProvider.ValueType | None = ...,
        ref: global___ConfigRef | None = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___SetConfigRequest = SetConfigRequest

@typing.final
class SetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetConfigResponse = SetConfigResponse

@typing.final
class UnsetConfigRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROVIDER_FIELD_NUMBER: builtins.int
    REF_FIELD_NUMBER: builtins.int
    provider: global___ConfigProvider.ValueType
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        provider: global___ConfigProvider.ValueType | None = ...,
        ref: global___ConfigRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___UnsetConfigRequest = UnsetConfigRequest

@typing.final
class UnsetConfigResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UnsetConfigResponse = UnsetConfigResponse

@typing.final
class ListSecretsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    INCLUDE_VALUES_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    module: builtins.str
    include_values: builtins.bool
    provider: global___SecretProvider.ValueType
    def __init__(
        self,
        *,
        module: builtins.str | None = ...,
        include_values: builtins.bool | None = ...,
        provider: global___SecretProvider.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_include_values", b"_include_values", "_module", b"_module", "_provider", b"_provider", "include_values", b"include_values", "module", b"module", "provider", b"provider"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_include_values", b"_include_values", "_module", b"_module", "_provider", b"_provider", "include_values", b"include_values", "module", b"module", "provider", b"provider"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_include_values", b"_include_values"]) -> typing.Literal["include_values"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_module", b"_module"]) -> typing.Literal["module"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___ListSecretsRequest = ListSecretsRequest

@typing.final
class ListSecretsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Secret(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REFPATH_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        refPath: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            refPath: builtins.str = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_value", b"_value", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_value", b"_value", "refPath", b"refPath", "value", b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_value", b"_value"]) -> typing.Literal["value"] | None: ...

    SECRETS_FIELD_NUMBER: builtins.int
    @property
    def secrets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListSecretsResponse.Secret]: ...
    def __init__(
        self,
        *,
        secrets: collections.abc.Iterable[global___ListSecretsResponse.Secret] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["secrets", b"secrets"]) -> None: ...

global___ListSecretsResponse = ListSecretsResponse

@typing.final
class GetSecretRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REF_FIELD_NUMBER: builtins.int
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        ref: global___ConfigRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ref", b"ref"]) -> None: ...

global___GetSecretRequest = GetSecretRequest

@typing.final
class GetSecretResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.bytes
    def __init__(
        self,
        *,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___GetSecretResponse = GetSecretResponse

@typing.final
class SetSecretRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROVIDER_FIELD_NUMBER: builtins.int
    REF_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    provider: global___SecretProvider.ValueType
    value: builtins.bytes
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        provider: global___SecretProvider.ValueType | None = ...,
        ref: global___ConfigRef | None = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___SetSecretRequest = SetSecretRequest

@typing.final
class SetSecretResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetSecretResponse = SetSecretResponse

@typing.final
class UnsetSecretRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROVIDER_FIELD_NUMBER: builtins.int
    REF_FIELD_NUMBER: builtins.int
    provider: global___SecretProvider.ValueType
    @property
    def ref(self) -> global___ConfigRef: ...
    def __init__(
        self,
        *,
        provider: global___SecretProvider.ValueType | None = ...,
        ref: global___ConfigRef | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_provider", b"_provider", "provider", b"provider", "ref", b"ref"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_provider", b"_provider"]) -> typing.Literal["provider"] | None: ...

global___UnsetSecretRequest = UnsetSecretRequest

@typing.final
class UnsetSecretResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UnsetSecretResponse = UnsetSecretResponse
